version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
  controller:
    image: dtr.corp.appdynamics.com/appdynamics/enterprise-console:latest
    container_name: controller
    ports:
      - "8080:8080"
      - "9080:9080"
      # elasticsearch uses 9200
      - "9201:9200"
  machine:
    container_name: machine
    environment:
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=SJ5b2m7d1$$354
      - APPDYNAMICS_CONTROLLER_HOST_NAME=controller
      - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
      - APPDYNAMICS_CONTROLLER_PORT=8080
      - EVENTS_SERVICE_HOST=controller
      - MACHINE_AGENT_PROPERTIES=-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=false
    build:
      context: .
      dockerfile: Dockerfile_MA
#      args:
#        - ENCRYPTION_KEY=${ENCRYPTION_KEY}
#        - PLAINTEXT_PWD=${PLAINTEXT_PWD}
    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local