### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###
# This will create this metric in all the tiers, under this path.
#metricPrefix: "Custom Metrics|Elasticsearch"

# This will create it in specific Tier aka Component. Replace <COMPONENT_ID>.
metricPrefix: "Server|Component:<ComponentID>|Custom Metrics|Elasticsearch"

servers:
  - displayName: Server1
    uri: "http://localhost:9200"
    username: ""
    password: ""
    encryptedPassword: ""

# To get the metrics through CAT apis
catEndpoints:
  - endpoint: "/_cat/health?v&"
    displayName: "Cluster Stats"
    metricPathKeys: ["cluster"]
    metrics:
      - name: ""
        alias: ""
        aggregationType: ""
        timeRollUpType: ""
        clusterRollUpType: ""

encryptionKey: ""

# number of concurrent tasks.
# This doesn't need to be changed unless many instances are configured
numberOfThreads: 5